In [3]:
import pandas as pd
import requests
import io

username = ""
token = ''


github_session = requests.Session()
github_session.auth = (username, token)

In [4]:
#Loading the file so we can be able to clean it

url = 'https://raw.githubusercontent.com/OmdenaAI/WeoWater/main/task-4-scraping-newspapers/labelled_data/merged_labeled_newspaper_data.csv?token=AHFHI4HVTOW7DZZM62NPBPLAXX2V4'

download = github_session.get(url).content #Reading and downloading the data

data = pd.read_csv(io.StringIO(download.decode('utf-8'))) #Converting the data into a pd dataframe

In [5]:
data.head(5)#Checking the first 5 rows in the data.

,Unnamed: 0,event_id,article_title,article_link,article_content,publishing_date,article_image,article_keywords,article_relevance,Country,...,Unnamed: 11,Unnamed: 9,Category,Unnamed: 10,Categories,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,0,Drought_Indonesia,"Worsening drought, clean water scarcity affect...",https://www.straitstimes.com/asia/se-asia/wors...,JAKARTA (THE JAKARTA POST/ASIA NEWS NETWORK) -...,"Wed, 30 Aug 2017 07:00:00 GMT",https://static.straitstimes.com.sg/s3fs-public...,"['worsening', 'agency', 'sabu', 'reservoirs', ...",,Indonesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Drought_Indonesia,How Indonesia's President monitors food securi...,https://govinsider.asia/inclusive-gov/pulse-la...,Indonesia is under threat of food insecurity a...,"Thu, 24 Aug 2017 07:00:00 GMT",https://govinsider.asia/wp-content/uploads/201...,"['data', 'better', 'usher', 'help', 'haze', 'm...",,Indonesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Drought_Indonesia,Amazing facts about Indonesia - Telegraph.co.uk,https://www.telegraph.co.uk/travel/destination...,Indonesia is celebrating 72 years of independe...,"Thu, 17 Aug 2017 07:00:00 GMT",https://www.telegraph.co.uk/content/dam/Travel...,"['including', 'biggest', 'amazing', 'credit', ...",,Indonesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Drought_Indonesia,Secrets behind ancient Sriwijaya spice trade -...,https://www.thejakartapost.com/adv/2017/08/04/...,Share this article Whatsapp\n\nFacebook\n\nTwi...,"Fri, 04 Aug 2017 07:00:00 GMT",https://img.jakpost.net/c/2017/08/03/2017_08_0...,"['sriwijaya', 'secrets', 'spices', 'bambang', ...",,Indonesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Drought_Indonesia,First real test for Jokowi on haze as annual f...,https://news.mongabay.com/2017/08/indonesian-p...,Land and forest fires have broken out in pocke...,"Tue, 08 Aug 2017 07:00:00 GMT",https://imgs.mongabay.com/wp-content/uploads/s...,"['annual', 'real', 'haze', 'season', 'regions'...",,Indonesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Dropping unnecessary columns

data.drop(data.columns[data.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)#Dropping unnamed columns in the file

to_drop = ['category','Categories',]#Columns to be dropped 

data.drop(to_drop, inplace = True, axis = 1)
data.head(5)#Checking if the correct columns have been dropped

,event_id,article_title,article_link,article_content,publishing_date,article_image,article_keywords,article_relevance,Country,Category
0,Drought_Indonesia,"Worsening drought, clean water scarcity affect...",https://www.straitstimes.com/asia/se-asia/wors...,JAKARTA (THE JAKARTA POST/ASIA NEWS NETWORK) -...,"Wed, 30 Aug 2017 07:00:00 GMT",https://static.straitstimes.com.sg/s3fs-public...,"['worsening', 'agency', 'sabu', 'reservoirs', ...",,Indonesia,NaN
1,Drought_Indonesia,How Indonesia's President monitors food securi...,https://govinsider.asia/inclusive-gov/pulse-la...,Indonesia is under threat of food insecurity a...,"Thu, 24 Aug 2017 07:00:00 GMT",https://govinsider.asia/wp-content/uploads/201...,"['data', 'better', 'usher', 'help', 'haze', 'm...",,Indonesia,NaN
2,Drought_Indonesia,Amazing facts about Indonesia - Telegraph.co.uk,https://www.telegraph.co.uk/travel/destination...,Indonesia is celebrating 72 years of independe...,"Thu, 17 Aug 2017 07:00:00 GMT",https://www.telegraph.co.uk/content/dam/Travel...,"['including', 'biggest', 'amazing', 'credit', ...",,Indonesia,NaN
3,Drought_Indonesia,Secrets behind ancient Sriwijaya spice trade -...,https://www.thejakartapost.com/adv/2017/08/04/...,Share this article Whatsapp\n\nFacebook\n\nTwi...,"Fri, 04 Aug 2017 07:00:00 GMT",https://img.jakpost.net/c/2017/08/03/2017_08_0...,"['sriwijaya', 'secrets', 'spices', 'bambang', ...",,Indonesia,NaN
4,Drought_Indonesia,First real test for Jokowi on haze as annual f...,https://news.mongabay.com/2017/08/indonesian-p...,Land and forest fires have broken out in pocke...,"Tue, 08 Aug 2017 07:00:00 GMT",https://imgs.mongabay.com/wp-content/uploads/s...,"['annual', 'real', 'haze', 'season', 'regions'...",,Indonesia,NaN

In [17]:
data.dtypes.value_counts()

object    10
dtype: int64

In [25]:
print(data.isnull().sum())#Checking missing values
data.drop('Category', inplace = True, axis = 1 )# dropping the column Category so we can clean the rest of the data
data.dropna(inplace = True)# dropping all the null values
print('')
print(data.isnull().sum())

event_id             0
article_title        0
article_link         0
article_content      0
publishing_date      0
article_image        0
article_keywords     0
article_relevance    0
Country              0
dtype: int64

event_id             0
article_title        0
article_link         0
article_content      0
publishing_date      0
article_image        0
article_keywords     0
article_relevance    0
Country              0
dtype: int64

In [26]:
data.shape #Checking how many rows and columns we have left

(2948, 9)

In [30]:
data['category']=''
data.head(5)

,event_id,article_title,article_link,article_content,publishing_date,article_image,article_keywords,article_relevance,Country,category
0,Drought_Indonesia,"Worsening drought, clean water scarcity affect...",https://www.straitstimes.com/asia/se-asia/wors...,JAKARTA (THE JAKARTA POST/ASIA NEWS NETWORK) -...,"Wed, 30 Aug 2017 07:00:00 GMT",https://static.straitstimes.com.sg/s3fs-public...,"['worsening', 'agency', 'sabu', 'reservoirs', ...",,Indonesia,
1,Drought_Indonesia,How Indonesia's President monitors food securi...,https://govinsider.asia/inclusive-gov/pulse-la...,Indonesia is under threat of food insecurity a...,"Thu, 24 Aug 2017 07:00:00 GMT",https://govinsider.asia/wp-content/uploads/201...,"['data', 'better', 'usher', 'help', 'haze', 'm...",,Indonesia,
2,Drought_Indonesia,Amazing facts about Indonesia - Telegraph.co.uk,https://www.telegraph.co.uk/travel/destination...,Indonesia is celebrating 72 years of independe...,"Thu, 17 Aug 2017 07:00:00 GMT",https://www.telegraph.co.uk/content/dam/Travel...,"['including', 'biggest', 'amazing', 'credit', ...",,Indonesia,
3,Drought_Indonesia,Secrets behind ancient Sriwijaya spice trade -...,https://www.thejakartapost.com/adv/2017/08/04/...,Share this article Whatsapp\n\nFacebook\n\nTwi...,"Fri, 04 Aug 2017 07:00:00 GMT",https://img.jakpost.net/c/2017/08/03/2017_08_0...,"['sriwijaya', 'secrets', 'spices', 'bambang', ...",,Indonesia,
4,Drought_Indonesia,First real test for Jokowi on haze as annual f...,https://news.mongabay.com/2017/08/indonesian-p...,Land and forest fires have broken out in pocke...,"Tue, 08 Aug 2017 07:00:00 GMT",https://imgs.mongabay.com/wp-content/uploads/s...,"['annual', 'real', 'haze', 'season', 'regions'...",,Indonesia,

In [31]:
data.to_csv('cleaned_merged_labbeled_newspaper_data.csv')