In [ ]:
# Libraries needed for the tutorial

import pandas as pd
import requests
import io
# Username of your GitHub account

username = ''

# Personal Access Token (PAO) from your GitHub account

token = ''

# Creates a re-usable session object with your creds in-built

github_session = requests.Session()
github_session.auth = (username, token)
#https://raw.githubusercontent.com/OmdenaAI/WeoWater/main/task-4-scraping-newspapers/output_to_clean/Drought/8%20-%20DR-2019-000034-LKA.csv?token=ANPNAAOEBRJRC4KXH3V5W6LAYXGSW
# Downloading the csv file from your GitHub

url = "https://raw.githubusercontent.com/OmdenaAI/WeoWater/main/task-3-wrangling-preprocessing/Twitter%20%26%20News%20Articles%20combined.csv?token=ANPNAANPOZ6ZVJKHDERF6ATA3MTDO" # Make sure the url is the raw version of the file on GitHub
download = github_session.get(url).content

# Reading the downloaded content and making it a pandas dataframe

twitter_news_articles = pd.read_csv(io.StringIO(download.decode('utf-8')))
print(twitter_news_articles.shape)
# Printing out the first 5 rows of the dataframe to make sure everything is good
twitter_news_articles.head()

(5713, 190)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

                   Id  ... Unnamed: 189
0  DR-2014-000109-CHN  ...          NaN
1  DR-2014-000109-CHN  ...          NaN
2  DR-2014-000109-CHN  ...          NaN
3  DR-2014-000109-CHN  ...          NaN
4  DR-2014-000109-CHN  ...          NaN

[5 rows x 190 columns]

In [ ]:
from google.colab import files

twitter_news_articles.to_csv('cleaned_twitter_news_articles.csv')
files.download('cleaned_twitter_news_articles.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files

Mounted at /content/drive

In [ ]:
twitter_news_articles = pd.read_csv('twitter_news_articles.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,3,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
print(twitter_news_articles.shape)
x =twitter_news_articles.drop_duplicates()
print(x.shape)
x

(5713, 192)
(5713, 192)

      Unnamed: 0  Unnamed: 0.1  ... Unnamed: 188 Unnamed: 189
0              0             0  ...          NaN          NaN
1              1             1  ...          NaN          NaN
2              2             2  ...          NaN          NaN
3              3             3  ...          NaN          NaN
4              4             4  ...          NaN          NaN
...          ...           ...  ...          ...          ...
5708        5708          5708  ...          NaN          NaN
5709        5709          5709  ...          NaN          NaN
5710        5710          5710  ...          NaN          NaN
5711        5711          5711  ...          NaN          NaN
5712        5712          5712  ...          NaN          NaN

[5713 rows x 192 columns]

In [ ]:
twitter_news_articles.category.unique()

array(['drought', 'none', 'flood_and_drought', 'flood', 'climate_change',
       'tree', ' e mais adequado',
       ' já que as rugosidades ressecadas de Ardeth Bay relembram a podridão da múmia com mais sutileza',
       ' sendo que fica ainda mais claro que todos eventos aterradores causados pela figura são'],
      dtype=object)

In [ ]:
twitter_news_articles = twitter_news_articles.replace(['flood_drought'],'flood_and_drought')

In [ ]:
twitter_news_articles = twitter_news_articles.replace(['climate_change'],'none')

In [ ]:
twitter_news_articles = twitter_news_articles.replace([' sendo que fica ainda mais claro que todos eventos aterradores causados pela figura são'],'none')

In [ ]:
u = twitter_news_articles[twitter_news_articles.category== 'sendo que fica ainda mais claro que todos eventos aterradores causados pela figura são']
u

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, Id, title, time, keywords, data source, category, country, source URL, body, language, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15, Unnamed: 16, Unnamed: 17, Unnamed: 18, Unnamed: 19, Unnamed: 20, Unnamed: 21, Unnamed: 22, Unnamed: 23, Unnamed: 24, Unnamed: 25, Unnamed: 26, Unnamed: 27, Unnamed: 28, Unnamed: 29, Unnamed: 30, Unnamed: 31, Unnamed: 32, Unnamed: 33, Unnamed: 34, Unnamed: 35, Unnamed: 36, Unnamed: 37, Unnamed: 38, Unnamed: 39, Unnamed: 40, Unnamed: 41, Unnamed: 42, Unnamed: 43, Unnamed: 44, Unnamed: 45, Unnamed: 46, Unnamed: 47, Unnamed: 48, Unnamed: 49, Unnamed: 50, Unnamed: 51, Unnamed: 52, Unnamed: 53, Unnamed: 54, Unnamed: 55, Unnamed: 56, Unnamed: 57, Unnamed: 58, Unnamed: 59, Unnamed: 60, Unnamed: 61, Unnamed: 62, Unnamed: 63, Unnamed: 64, Unnamed: 65, Unnamed: 66, Unnamed: 67, Unnamed: 68, Unnamed: 69, Unnamed: 70, Unnamed: 71, Unnamed: 72, Unnamed: 73, Unnamed: 74, Unnamed: 75, Unnamed: 76, Unnamed: 77, Unnamed: 78, Unnamed: 79, Unnamed: 80, Unnamed: 81, Unnamed: 82, Unnamed: 83, Unnamed: 84, Unnamed: 85, Unnamed: 86, Unnamed: 87, Unnamed: 88, Unnamed: 89, Unnamed: 90, Unnamed: 91, Unnamed: 92, Unnamed: 93, Unnamed: 94, Unnamed: 95, Unnamed: 96, Unnamed: 97, ...]
Index: []

[0 rows x 192 columns]

In [ ]:
delete_row = twitter_news_articles[twitter_news_articles["category"]== 'já que as rugosidades ressecadas de Ardeth Bay relembram a podridão da múmia com mais sutileza'].index
twitter_news_articles = twitter_news_articles.drop(delete_row)
print(twitter_news_articles.shape)

(2488, 11)

In [ ]:
twitter_news_articles = twitter_news_articles.drop_duplicates(subset = 'title', keep = 'first')
print(twitter_news_articles.shape)

(2488, 11)

In [ ]:
print(twitter_news_articles.columns)

Index(['Unnamed: 0', 'Id', 'title', 'time', 'keywords', 'data source',
       'category', 'country', 'source URL', 'body', 'language', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62',
       'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66',
       'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70',
       'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74',
       'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78',
       'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82',
       'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86',
       'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89'],
      dtype='object')

In [ ]:
twitter_news_articles = twitter_news_articles.drop(['Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34',
       'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38',
       'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42',
       'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46',
       'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50',
       'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54',
       'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58',
       'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62',
       'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66',
       'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69', 'Unnamed: 70',
       'Unnamed: 71', 'Unnamed: 72', 'Unnamed: 73', 'Unnamed: 74',
       'Unnamed: 75', 'Unnamed: 76', 'Unnamed: 77', 'Unnamed: 78',
       'Unnamed: 79', 'Unnamed: 80', 'Unnamed: 81', 'Unnamed: 82',
       'Unnamed: 83', 'Unnamed: 84', 'Unnamed: 85', 'Unnamed: 86',
       'Unnamed: 87', 'Unnamed: 88', 'Unnamed: 89'], axis = 1)

In [ ]:
twitter_news_articles

      Unnamed: 0  ... language
0              0  ...  English
1              1  ...  English
2              2  ...  English
3              3  ...  English
4              4  ...  English
...          ...  ...      ...
3950        3950  ...  English
3951        3951  ...  English
3952        3952  ...  English
3953        3953  ...  English
3954        3954  ...       en

[2488 rows x 11 columns]

In [ ]:
twitter_news_articles = twitter_news_articles.drop(['Unnamed: 0'], axis = 1)

In [ ]:
twitter_news_articles.category.unique()

array(['drought', 'none', 'flood_and_drought', 'flood', 'tree'],
      dtype=object)

In [ ]:
twitter_news_articles.columns

Index(['Id', 'title', 'time', 'keywords', 'data source', 'category', 'country',
       'source URL', 'body', 'language'],
      dtype='object')